configuration:
  model: "NB"
  src: data/bronte
  repetitions: 5
  skip:
    - preprocessing
  clean:
    - results
    - separations
    # - segments

authors:
  Anne Bronte: anne
  Charlotte Bronte: charlotte
  Emily Bronte: emily

segmenters:
  - src: corpus/Anne*.txt
    author: Anne Bronte
    size: 20
  - src: corpus/Charlotte*.txt
    author: Charlotte Bronte
    size: 20
  - src: corpus/Emily*.txt
    author: Emily Bronte
    size: 20

preprocessors:
  # - text
  # - pos
  # - constituency
  - ccg

separations:
  - author: Anne Bronte
    holdout: 0.2
  - author: Charlotte Bronte
    holdout: 0.2
  - author: Emily Bronte
    holdout: 0.2

features:
  - name: word_length
  - name: word_frequency
    filename: resources/function_words.txt
  - name: ngram
    length: 5
    type: ccg
    threshold: 150
  - name: ngram
    length: 4
    type: ccg
    threshold: 150
  - name: ngram
    length: 3
    type: ccg
    threshold: 150
  - name: ngram
    length: 2
    type: ccg
    threshold: 150
