configuration:
  src: data/bronte
  train: 0.8
  accuracy: 0.6 # accuracy estimation
  skip:
    -
    # - preprocessing
  clean:
    - composite

authors:
  Anne Bronte: anne
  Charlotte Bronte: charlotte
  Emily Bronte: emily

corpus:
  - src: corpus/Anne*.txt
    author: Anne Bronte
  - src: corpus/Charlotte*.txt
    author: Charlotte Bronte
  - src: corpus/Emily*.txt
    author: Emily Bronte

generate:
  n: 10
  stay: 0.95
  terminate: 0.01
  threshold: 50 # sentence threshold

preprocessors:
  - text
  - pos
  - ccg
  - redacted
  - paths
  - cpfws

features:
  - name: ngram
    length: 1
    type: redacted
    threshold: 30
  - name: ngram
    length: 2
    type: redacted
    threshold: 30
  - name: ngram
    length: 3
    type: redacted
    threshold: 30

non_features:
  - name: word_frequency
    filename: resources/function_words.txt
  - name: ngram
    length: 1
    type: cpfws
    threshold: 40
