configuration:
  src: data/bronte
  train: 0.8
  accuracy: 0.7179 # accuracy estimation
  skip:
    -
    # - preprocessing
  clean:
    - composite

authors:
  Anne Bronte: anne
  Charlotte Bronte: charlotte
  Emily Bronte: emily

corpus:
  - src: corpus/Anne*.txt
    author: Anne Bronte
  - src: corpus/Charlotte*.txt
    author: Charlotte Bronte
  - src: corpus/Emily*.txt
    author: Emily Bronte

generate:
  n: 3
  stay: 0.95
  terminate: 0.01
  threshold: 50 # sentence threshold

preprocessors:
  - text
  - pos
  - ccg

features:
  - name: word_length
  - name: ngram
    length: 6
    type: ccg
    threshold: 10
  - name: ngram
    length: 5
    type: ccg
    threshold: 10
  - name: ngram
    length: 4
    type: ccg
    threshold: 10
  - name: ngram
    length: 3
    type: ccg
    threshold: 10
  - name: ngram
    length: 2
    type: ccg
    threshold: 10
  - name: ngram
    length: 6
    type: pos
    threshold: 10
  - name: ngram
    length: 5
    type: pos
    threshold: 10
  - name: ngram
    length: 4
    type: pos
    threshold: 10
  - name: ngram
    length: 3
    type: pos
    threshold: 10
  - name: ngram
    length: 2
    type: pos
    threshold: 10
