configuration:
  src: data/bronte
  train: 0.8
  accuracy: 0.6 # accuracy estimation
  skip:
    # - none
    - preprocessing
  clean:
    - composite
  sentence_dir: adj_sentences1

authors:
  Anne Bronte: anne
  Charlotte Bronte: charlotte
  Emily Bronte: emily

corpus:
  - src: corpus/Anne*.txt
    author: Anne Bronte
  - src: corpus/Charlotte*.txt
    author: Charlotte Bronte
  - src: corpus/Emily*.txt
    author: Emily Bronte

generate:
  n: 10
  stay: 0.95
  terminate: 0.01
  threshold: 50 # sentence threshold

preprocessors:
  - text
  - pos
  - ccg
  - redacted
  - paths
  - cpfws
  - constituency

features_cpfws:
  - name: ngram
    length: 1
    type: cpfws
    threshold: 5

features:
  - name: ngram
    length: 1
    type: pos
    threshold: 5
  - name: ngram
    length: 2
    type: pos
    threshold: 5
  - name: ngram
    length: 3
    type: pos
    threshold: 5

features_freq:
  - name: word_frequency
    filename: resources/function_words.txt
